# Generated by Django 5.1.4 on 2024-12-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_make_alter_car_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='plate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
